### PR TITLE
Allow sending messages longer than 4096 chars

### PR DESCRIPTION
**Pull request by laurynas-karvelis**
This will split message into 4096 char chunks and send one after another.

### CODE REVIEW

**Comment by mdibaiee** [comment]
@laurynas-karvelis Hey! Thanks for this, I think we should move the handling of this case to [`Message.js`](https://github.com/mdibaiee/node-telegram-api/blob/master/src/types/Message.js#L96) and set a custom `send` method instead of the `if` statement in `Base.js`, what do you think?

**Comment by laurynas-karvelis** [comment]
This is what I've achieved so far, I suppose this makes sense.
Edit: bump :)

**Review by mdibaiee — APPROVED** [review]
Sorry for the delay, I had forgotten about this since the notification was already marked as read.

Looks good, thanks a lot!
By the way, I would like to make you a collaborator on the repository, do you mind if I add you to the npm package and GitHub repository as a collaborator? Pull-requests are going to be necessary still but I want you to have more control :grin: - If so, please send me your npm credentials as well

**Comment by mdibaiee** [comment]
Published `telegram-api@3.0.0`

**Comment by laurynas-karvelis** [comment]
Hi @mdibaiee, sorry for such a long response :). I'd like to keep contributing once in a while by submitting PRs instead of being repo collaborator. I'm not sure how actively I'll keep on developing with this module, hence won't be able to stay always up-to-date with the codebase etc.
I might come back with additional PR sometime soon-ish regards persisting Markdown/HTML structure once a long message gets split up into multiple 4Kb chunks.

**Comment by mdibaiee** [comment]
@laurynas-karvelis I understand, I would like to thank you for your contributions anyways. :grin::+1:

**Comment by laurynas-karvelis** [comment]
Thank You for this great module :)

**Pull request merged**
